export const fakeData = {
  kind: 'youtube#videoListResponse',
  etag: '"SJZWTG6xR0eGuCOh2bX6w3s4F94/1gL0ZOWNkPbcqxfHIZenNtc3tEc"',
  pageInfo: {
    totalResults: 1,
    resultsPerPage: 1,
  },
  items: [
    {
      kind: 'youtube#video',
      etag: '"SJZWTG6xR0eGuCOh2bX6w3s4F94/iNEXi_6LFu2V2oTbkjeRn695zoo"',
      id: 'PufZCu49X6k',
      snippet: {
        publishedAt: '2020-02-28T19:03:13.000Z',
        channelId: 'UCaxar6TBM-94_ezoS00fLkA',
        title:
          'Kroxa Discard Aggro Escape - Mythic Laddering | Theros Beyond Death | MTG Arena',
        description:
          "How have the best decks in the format evolved since the World Championship? Lets investigate and hopefully climb up the Mythic Ladder! Ending the day on a Kroxa Discard Aggro Escape Enchantments Thing.\nList:\n4 Kroxa, Titan of Death's Hunger (THB) 221\n7 Swamp (THB) 283\n7 Mountain (THB) 285\n2 The Akroan War (THB) 124\n4 Mire Triton (THB) 105\n2 Phoenix of Ash (THB) 148\n4 Mogis's Favor (THB) 107\n4 Tymaret Calls the Dead (THB) 118\n3 Mire's Grasp (THB) 106\n4 Agonizing Remorse (THB) 83\n4 Blood Crypt (RNA) 245\n4 Temple of Malice (THB) 247\n4 Hateful Eidolon (THB) 101\n3 Aphemia, the Cacophony (THB) 84\n2 Fabled Passage (ELD) 244\n2 Dead Weight (GRN) 67\n\nFor more of Day9's MTG Arena, Theros Beyond Death gameplay:\nhttps://www.youtube.com/playlist?list=PLgmCLtUkEutIrnm7BfATEXw1TxqlCWEXJ\n-----------------------------------------------------------------------------------\nWatch live on Twitch: https://www.twitch.tv/day9tv/\nCheck out my Website: https://day9.tv/store/\nDay[9] Merch: https://day9.tv/store/",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/PufZCu49X6k/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/PufZCu49X6k/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/PufZCu49X6k/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/PufZCu49X6k/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/PufZCu49X6k/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Day9TV',
        tags: [
          'Day9',
          'Day[9]',
          'Day9tv',
          'Sean Plott',
          'twitch',
          'games',
          'card games',
          'card game',
          'mtg',
          'mtg arena',
          'mtga',
          'MTG:Arena',
          'magic the gathering',
          'magic',
          'gathering',
          'theros',
          'beyond',
          'death',
          'thb',
          'theros beyond death',
          'day9 theros beyond death',
          'day9 thb',
          'constructed',
          'thb constructed',
          'theros beyond death constructed',
          'standard',
          'theros beyond death standard',
          'thb standard',
          'top standard decks',
          'top standard',
          'mythic',
          'laddering',
          'mythic laddering',
          'kroxa',
          'discard',
          'aggro',
          'escape',
        ],
        categoryId: '20',
        liveBroadcastContent: 'none',
        localized: {
          title:
            'Kroxa Discard Aggro Escape - Mythic Laddering | Theros Beyond Death | MTG Arena',
          description:
            "How have the best decks in the format evolved since the World Championship? Lets investigate and hopefully climb up the Mythic Ladder! Ending the day on a Kroxa Discard Aggro Escape Enchantments Thing.\nList:\n4 Kroxa, Titan of Death's Hunger (THB) 221\n7 Swamp (THB) 283\n7 Mountain (THB) 285\n2 The Akroan War (THB) 124\n4 Mire Triton (THB) 105\n2 Phoenix of Ash (THB) 148\n4 Mogis's Favor (THB) 107\n4 Tymaret Calls the Dead (THB) 118\n3 Mire's Grasp (THB) 106\n4 Agonizing Remorse (THB) 83\n4 Blood Crypt (RNA) 245\n4 Temple of Malice (THB) 247\n4 Hateful Eidolon (THB) 101\n3 Aphemia, the Cacophony (THB) 84\n2 Fabled Passage (ELD) 244\n2 Dead Weight (GRN) 67\n\nFor more of Day9's MTG Arena, Theros Beyond Death gameplay:\nhttps://www.youtube.com/playlist?list=PLgmCLtUkEutIrnm7BfATEXw1TxqlCWEXJ\n-----------------------------------------------------------------------------------\nWatch live on Twitch: https://www.twitch.tv/day9tv/\nCheck out my Website: https://day9.tv/store/\nDay[9] Merch: https://day9.tv/store/",
        },
      },
      statistics: {
        viewCount: '9351',
        likeCount: '131',
        dislikeCount: '5',
        favoriteCount: '0',
        commentCount: '16',
      },
    },
  ],
};
